server:
  port: 8081

spring:
  application:
    name: servicepayment


  cloud:
    function:
      definition: fraudTransactionConsumer

  data:
    mongodb:
      uri: mongodb://localhost:27017/service-payment-database

    stream:
      kafka:
        binder:
          brokers: localhost:9092

    bindings:
      transacaoAprovada-out-0:
        destination: transacao-aprovada-topic

      transacaoReprovada-out-0:
        destination: transacao-reprovada-topic

